server:
  port: 9090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:8761/eureka/   
  
zuul:
  host:
    connect-timeout-millis: 300000 # 5 min starting the connection 
    socket-timeout-millis: 300000  # monitor the continuous incoming data flow
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin 
  
  
  prefix: /api
  routes:
    account:
      path: /account/**     
      #serviceId: security-authorization
      url: http://${SECURITY_AUTHORIZATION_HOST:localhost}:9002/account
      sensitiveHeaders:
    tokens:
      path: /tokens/**     
      #serviceId: security-authorization
      url: http://${SECURITY_AUTHORIZATION_HOST:localhost}:9002/tokens
      sensitiveHeaders:
    oauth:
      path: /oauth/**     
      sensitiveHeaders:
      url: http://${SECURITY_AUTHORIZATION_HOST:localhost}:9002/oauth
      #serviceId: security-authorization
      
    security-authorization:
      stripPrefix: false
      path: /security/authorization/**
      #serviceId: security-authorization
      url: http://${SECURITY_AUTHORIZATION_HOST:localhost}:9002
      
    financeiro-planocontas:
      stripPrefix: false
      path: /financeiro/plano_contas/**
      serviceId: financeiro-planocontas
      
    financeiro-contaspagar:
      stripPrefix: false
      path: /financeiro/contas_pagar/**
      serviceId: financeiro-contaspagar
      
    financeiro-contasreceber:
      stripPrefix: false
      path: /financeiro/contas_receber/**
      serviceId: financeiro-contasreceber
      
    financeiro-fluxocaixa:
      stripPrefix: false
      path: /financeiro/fluxo_caixa/**
      serviceId: financeiro-fluxocaixa
      
    cadastros-fornecedor:
      stripPrefix: false
      path: /cadastros/fornecedor/**
      serviceId: cadastros-fornecedor
      
    cadastros-cliente:
      stripPrefix: false
      path: /cadastros/cliente/**
      serviceId: cadastros-cliente
      
    cadastros-banco:
      stripPrefix: false
      path: /cadastros/banco/**
      serviceId: cadastros-banco
      #url: http://localhost:9013
      
security:
  oauth2:
    resource:
      jwt:
        key-value: 123
        
ribbon:
    ReadTimeout: 300000
    ConnectTimeout: 300000        
        
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 300000        
        
logging: 
  level:
    org.org.springframework: DEBUG        